services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: tcc-app
    env_file:
      - .env
    ports:
      - "${APP_PORT}:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_CHARSET: utf8mb4
    volumes:
      - ./:/var/www/html:cached
    depends_on:
      - db

  db:
    image: mysql:${MYSQL_VERSION}
    container_name: tcc-db
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

volumes:
  dbdata:
